---
title: "First Knit"
author: "Sonya Soto"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended Antelope Valley High school, I graduated in 1992. English I had Dr Wood as my professor and math unfortunately cannot remember my math instructor. The subject I did best in was Math. I find Math very interesting and challenging compared to Enlish class.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
 I have an Apple PC at home I can use. I rate myself a 5 on a scale of 1-10, 1 being a total dummy and 10 being a geek.I have internet access available at home. My internet connection I use is Spectrum and so far I have not had any issues at all.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I would prefer to be called Sonya. I have many nick names my family and friends use to address me but here at school I prefer Sonya.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   I have been an LVN for 20 years and would like to some day obtain my RN degree. I have waited long enough. I would love to be a Registered Nurse for the State of California.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  I have never been out of he country. If I had an opportunity I to travel out of the country i would love to visit Spain and Italy. Unfortuanately I do not have any Millitary background.




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   This is the first time i have taken Statistics. I am aware Math 115 satisfies as a general education requirement which is great because it is a requirement for the RN brigde program.
 






  




